# NumPy Giriş

In [1]:
import numpy as np #kütüphanenin içeri aktarması

Neden Numpy Kullanmalıyız?

In [2]:
#örneğin iki tane vektörün çarpılması: normalde
a=[1,2,3,4]
b=[4,5,6,7]

ab=[]
for i in range(len(a)):
    ab.append(a[i]*b[i])
ab

[4, 10, 18, 28]

işlemin numpy ile yapılması

In [3]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a*b


array([ 4, 10, 18, 28])

## Numpy Arrayleri Oluşturma

### 1.listelerden Numpy Array Oluşturma

In [4]:
a=np.array([1,6,5,7])
print(a)
type(a) #a'nın tipinin sorgulanması

[1 6 5 7]


numpy.ndarray

In [5]:
b=np.array([10,15,16.3,4])
print(b)
type(b)

[10.  15.  16.3  4. ]


numpy.ndarray

In [6]:
b=np.array([10,15,16.3,4],dtype="int32")#dtype anahtar kelimesini kullanarak array içindeki değişkenlerin türünü belirleyebiliriz
print(b)
type(b)

[10 15 16  4]


numpy.ndarray

In [7]:
#sıfırlardan oluşan arrayler yaratmak için np.zeros'u kullanıyoruz
c=np.zeros(10,dtype=int)
print(c)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
#birlrden oluşan arrayler  tanımlmak için np.ones()'i kullanıyoruz.
d=np.ones((5,5))#5*5 matris
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


sadece istenile bir değerden matris oluşturmak için np.full() metodu kullanılır

In [9]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

belli bir aralıkta belli bir artış oranına sahip arrayler tanımlamak için np.arange() metodunu kullanırız

In [10]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

iki değer arasında belli sayıda değer üretmek için np.linspace() metodunu kullanırız

In [11]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

normal dağılıma sahip matrisler üretmek için np.random.normal() metodunu kullanırız

In [12]:
a=np.random.normal(1,2,(5,5))#ilk parametre ortalama ikinci parametre standart sapma
print(a)
print("standart sapma",np.std(a))
print("ortalama",np.mean(a))

[[ 5.98306068  2.0341242   1.72012285  0.53705436  2.60275687]
 [-1.8746441   0.44675607  2.61769023  0.80690844 -0.83067245]
 [ 1.37478284  3.4792159   1.85969969  2.17407518  0.22622517]
 [ 2.03779736  0.72797779  2.81099678  2.20823671  1.50859305]
 [ 3.61751501  2.58123616  0.66898616  0.50325081  1.62020364]]
standart sapma 1.5258950540214657
ortalama 1.6576779764378529


belli bir aralıktaki integer değerleden oluşan bir matris tanımlamak için np.random.randint() metodu kullanılır.

In [13]:
np.random.randint(0,10,(3,3))

array([[5, 6, 6],
       [6, 5, 4],
       [1, 7, 3]])

köşegen değerleri birlerden ve diğer elemanları sıfır olan matrisler üretmek için np.eye() metodunu kullanırız.

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NumPy Arraylerini biçimlendirme

In [15]:
a=np.random.randint(0,10,(6,5))#2 boyutlu array
#a matrisinin özelliklerini sorgulama
print("boyutu:",a.ndim)
print("şekli:",a.shape)
print("eleman sayısı:",a.size)
print("elemanların tipi:",a.dtype)

boyutu: 2
şekli: (6, 5)
eleman sayısı: 30
elemanların tipi: int32


In [16]:
a=np.random.randint(0,10,(3,5,2))#3 boyutlu array
#a matrisinin özelliklerini sorgulama
print("boyutu:",a.ndim)
print("şekli:",a.shape)
print("eleman sayısı:",a.size)
print("elemanların tipi:",a.dtype)

boyutu: 3
şekli: (3, 5, 2)
eleman sayısı: 30
elemanların tipi: int32


## Numpy Arraylerini yeniden Şekillendirme

In [17]:
a=np.arange(21)
print(a)
print("a'nın eleman sayısı",a.size)
#Not: burda a'yı yeniden şekilendirirken oluşturulan yeni a'nın şeklinin boyutu 
#a'nın eleman sayısının çarpanları olmalıdır
a=a.reshape((7,3))
print("anın yeniden şekillendirilmiş hali\n",a)
print("yeni şekillendirilmiş a'nı şekli",a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a'nın eleman sayısı 21
anın yeniden şekillendirilmiş hali
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
yeni şekillendirilmiş a'nı şekli (7, 3)


## NumPy Arraylerini Birleştirme

In [18]:
#tek boyutlu birleştirme
x=np.array([1,2,3])
y=np.array([4,5,6])

z=np.concatenate([x,y])
z

array([1, 2, 3, 4, 5, 6])

In [19]:
#iki boyutlu birleştirme
a=np.array([[1,2,3],
           [4,5,6]])

print(np.concatenate([a,a],axis=0))
print(np.concatenate([a,a],axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [20]:
#boyutları farklı olan arrayleri birleştirme alt alta sütun boyutları aynı olmalı
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([4,6,9])
np.vstack([b,a])

array([[4, 6, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
#boyutları farklı olan arrayleri birleştirme yan yana satır boyutları aynı olmalı
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([[1],
            [2]])
np.hstack([a,b])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

## Array Ayırma İşlemleri

In [22]:
x=np.arange(1,20,2)
a,b,c=np.split(x,[3,7])#[3,7] nerden ayırmak istediğimiz
print(a,b,c)

[1 3 5] [ 7  9 11 13] [15 17 19]


In [23]:
m=np.arange(16).reshape((4,4))
print(m)
#dikey ayırma
satır12,satır34=np.vsplit(m,[2])
print("satır12:\n",satır12)
print("satır34:\n",satır34)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
satır12:
 [[0 1 2 3]
 [4 5 6 7]]
satır34:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [24]:
#yatay ayırma
m=np.arange(16).reshape((4,4))
print(m)
sutun12,sutun34=np.hsplit(m,[2])
print("sutun12:\n",sutun12)
print("sutun12:\n",sutun34)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sutun12:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
sutun12:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Array Sıralama İşlemleri

In [25]:
t=np.array([np.random.randint(0,20,10)])
print("array",t)

#küçükten büyüğe doğru sıralam
print("sırali array",np.sort(t))
#NOT: np.sort metodunu kullandığımız zaman orjinal arrayde değişiklik olmaz
#ama t.sort() yaptığımız zaman orjinal arrayde değişir

array [[ 9  5  6 14  8  2  6 12 17 15]]
sırali array [[ 2  5  6  6  8  9 12 14 15 17]]


In [26]:
#eğer sıralama yaptıktan sonra orjinal arraydeki sayıların indekslerini tutmak istiyorsak
#np.argsort() metodu kullanılır
t=np.array([np.random.randint(0,20,10)])
i=np.argsort(t)
print("orjinal array",t)
print("sirali array",np.sort(t))
print("orjinal arraydeki indexi",i)

#orjinal arrayimiz iki boyutlu. yukarıdakş i'nin ne işe yaradığını bulmak için aşağıdaki kod  satırını çalıştıralım

v=t[0][i]
print("indexin orjinal arrayde yerine konulması",v)#sıralı array ile aynı oldı :)




orjinal array [[ 9 18  8 16  9 17  8  5  5  2]]
sirali array [[ 2  5  5  8  8  9  9 16 17 18]]
orjinal arraydeki indexi [[9 7 8 2 6 0 4 3 5 1]]
indexin orjinal arrayde yerine konulması [[ 2  5  5  8  8  9  9 16 17 18]]


## Numpy Eleman İşlemleri

In [27]:
#tek boyutlu
a=np.random.randint(10,size=10)
print(a)
print("ilk eleman:",a[0]) #ilk eleman
print("ilk eleman:",a[-1]) #son eleman
a[0]=25 #eleman değerini değiştirme
print(a)

[3 0 1 3 2 3 3 3 0 7]
ilk eleman: 3
ilk eleman: 7
[25  0  1  3  2  3  3  3  0  7]


In [28]:
#iki boyutlu
a=np.random.randint(10,size=(5,6))
print(a)
print("ilk eleman: (0,0) >",a[0][0])
print("son eleman:(4,4)  >",a[4][4])
a[3][2]=12 #veya a[3,2]
print(a)
a[3,2]=12
print(a)

[[5 3 9 0 0 1]
 [9 4 8 4 5 5]
 [0 5 3 6 4 0]
 [6 7 0 8 3 6]
 [0 4 1 0 1 6]]
ilk eleman: (0,0) > 5
son eleman:(4,4)  > 1
[[ 5  3  9  0  0  1]
 [ 9  4  8  4  5  5]
 [ 0  5  3  6  4  0]
 [ 6  7 12  8  3  6]
 [ 0  4  1  0  1  6]]
[[ 5  3  9  0  0  1]
 [ 9  4  8  4  5  5]
 [ 0  5  3  6  4  0]
 [ 6  7 12  8  3  6]
 [ 0  4  1  0  1  6]]


not: numpy arrayi içindeki değerler tek tiptir.

In [29]:
a=np.random.randint(10,size=(5,6))
print(a)
print(a.dtype)
#örneğin arraydekş bir değeri float ile değiştirelim
a[0,0]=3.5
print(a)#görüldüğü gibi float sayının integ kısmı tek alınmış

[[5 7 6 6 5 7]
 [1 2 8 5 9 9]
 [4 0 4 8 7 8]
 [6 2 5 5 7 6]
 [4 1 2 3 0 9]]
int32
[[3 7 6 6 5 7]
 [1 2 8 5 9 9]
 [4 0 4 8 7 8]
 [6 2 5 5 7 6]
 [4 1 2 3 0 9]]


## slicing ile Arrayin alt kümelerine Erişim
belli aralıktaki değerleri seçmek için kullanılır

In [30]:
#tek boyutlu
a=np.arange(20,30)
b=a[0:3] #anın ilk üç elemanını seç veya a[:3]
print("a:",a)
print("b:",b)
#anın 3 ten sonraki tüm elemanlarını seçmek için
c=a[3:]
print("c:",c)
#elemanları ikişer ikişer atlayarak seçmek için
d=a[::2]
print("d:",d)


a: [20 21 22 23 24 25 26 27 28 29]
b: [20 21 22]
c: [23 24 25 26 27 28 29]
d: [20 22 24 26 28]


In [31]:
#iki boytlu
a=np.random.randint(10,size=(5,5))
#1. sütuna erişmek için 
b=a[:,0]#virgülden önceki kısım satırlar sonraki ise sütunlar ":" tüm satır veya sütunları seç
print("a\n",a)
print("b\n",b)

#2.satıra erişmek için
c=a[1,:]
print("c\n",c)

#belli bir satır ve sütna erişmek için
d=a[:2,:3]# 0,1. satırı ve 0,1,2. sütundaki elemanları al veya d=a[0:2,0:3]
print("d\n",d)
#tüm satırları ve ilk iki sütunu seçmek için
e=a[::,0:2] #veya a[:,:2]
print("e\n",e)

a
 [[9 5 2 0 9]
 [3 0 2 1 5]
 [4 8 9 3 0]
 [1 8 3 2 7]
 [1 8 2 6 3]]
b
 [9 3 4 1 1]
c
 [3 0 2 1 5]
d
 [[9 5 2]
 [3 0 2]]
e
 [[9 5]
 [3 0]
 [4 8]
 [1 8]
 [1 8]]


## Array Alt Kümelerini Bağımszlaştırma


Not : slicing işlemleri yaparak seçtiğimiz alt kümeler üzerinde değişiklik 
    yaptığımız zaman bu değişiklik ana kümeyede yansır...

In [32]:
a=np.random.randint(10,size=(5,5))
#1. sütuna erişmek için 
b=a[0:3,0:2]#virgülden önceki kısım satırlar sonraki ise sütunlar ":" tüm satır veya sütunlarıseç
print("a\n",a)
print("b\n",b)
b[1,0]=999
b[2,0]=999
print("a\n",a)
#burdanda görüldüğü gibi b üzerinde yaptığımız değişikler a üzerindede değişikliğe sebep oldu
#bunu engllemek için copy() metodu kullanılır
e=a[1:3,2:4].copy()
print("e\n",e)
e[0,0]=1998
print("e\n",e)
print("a\n",a)


a
 [[1 8 0 4 0]
 [9 0 6 4 2]
 [3 3 9 4 8]
 [8 0 6 3 4]
 [9 1 0 2 0]]
b
 [[1 8]
 [9 0]
 [3 3]]
a
 [[  1   8   0   4   0]
 [999   0   6   4   2]
 [999   3   9   4   8]
 [  8   0   6   3   4]
 [  9   1   0   2   0]]
e
 [[6 4]
 [9 4]]
e
 [[1998    4]
 [   9    4]]
a
 [[  1   8   0   4   0]
 [999   0   6   4   2]
 [999   3   9   4   8]
 [  8   0   6   3   4]
 [  9   1   0   2   0]]


## Fancy İndex ile Eleman İşlemleri
birden fazla index seçiminde kullanılır

In [33]:
#tek boyutlu dizilerde
v=np.arange(0,30,3)
#istenen indexteki değerleri bir array veya liste yardımıyla ana arrayden çekeriz
print("v",v)
indexler=[1,3,7]
b=v[indexler] # veya v[[1,3,7]] liste kullanmadan
print("b",b)


v [ 0  3  6  9 12 15 18 21 24 27]
b [ 3  9 21]


In [34]:
#iki boyutlu dizilerde
a=np.arange(9).reshape(3,3)
print("a\n",a)
satir=np.array([1,2])
sutun=[0,2]
b=a[satir,sutun]#[1,0]. elemanı ve [2,2]. elemanı seç
print("b",b)

#herhangi bir satırı ve 1'den fazla sütun seçmek çin
c=a[0,[1,2]]#[0,0]. elemanı ve [0,1]. elemanı seç
print("c",c)
#tüm satırları ve belli sütundaki değerleri seçmek için
d=a[:,[0,2]]#[[0,0],[0,2],[1,0],...]
print("d\n",d)

a
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b [3 8]
c [1 2]
d
 [[0 2]
 [3 5]
 [6 8]]


## Karşılaştırma Operatörleri ile True-False  Sorgulaması

In [35]:
a=np.array(np.random.randint(12,size=(4,3)))
print("a\n",a)
print("a>3\n",a>3)#a>3=True Değilse False
print("a<=7\n",a<=7)#a<=7=True Değilse False
print("a==5\n",a==3)#a==5=True Değilse False
print("a!=10\n",a!=10)#a eşit değil 10=True Değilse False

a
 [[ 6  9  4]
 [ 0  5  1]
 [ 0  6  8]
 [ 4 11  9]]
a>3
 [[ True  True  True]
 [False  True False]
 [False  True  True]
 [ True  True  True]]
a<=7
 [[ True False  True]
 [ True  True  True]
 [ True  True False]
 [ True False False]]
a==5
 [[False False False]
 [False False False]
 [False False False]
 [False False False]]
a!=10
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## iki Array'i Karşılaştırma

In [36]:
a=np.array(np.random.randint(12,size=(4,3)))
print("a\n",a)
b=np.array(np.random.randint(12,size=(4,3)))
print("b\n",b)
print("a > b \n",a>b)
print("a == b \n",a==b)
print("5'ten büyük değerlerin sayısı:",np.sum(a>5))

a
 [[11  9 10]
 [ 5  6 10]
 [ 7  6 11]
 [ 1 10 10]]
b
 [[ 1  1  7]
 [ 2  2  5]
 [ 3 11  6]
 [ 3 10 10]]
a > b 
 [[ True  True  True]
 [ True  True  True]
 [ True False  True]
 [False False False]]
a == b 
 [[False False False]
 [False False False]
 [False False False]
 [False  True  True]]
5'ten büyük değerlerin sayısı: 10


### satır ve sütün bazında karşılaştırma ifadeleri

In [37]:
a=np.array(np.random.randint(12,size=(4,3)))
print("a\n",a)
print("satırlardaki 3'ten büyük değer sayısı:",np.sum(a>3,axis=1))
print("sütunardaki 3'ten büyük değer sayısı:",np.sum(a>3,axis=0))

a
 [[5 8 2]
 [9 9 5]
 [2 3 0]
 [8 3 9]]
satırlardaki 3'ten büyük değer sayısı: [2 3 0 2]
sütunardaki 3'ten büyük değer sayısı: [3 2 2]


#### aynı anda tüm elemanların bir koşulu sağlayı veya sağlayamadığı

In [38]:
a=np.array(np.random.randint(12,size=(4,3)))
print("a\n",a)
#a array'inin içindeki tüm elemanları 5 'ten büyük olup olmadığının sorglanması
print("tüm elemanlar 5'ten büyükmü:",np.all(a>5))
#arrayin tüm elemanları içinde yalnız bir tanesi şartı sağlıyormu
print("5'ten büyük değer varmı:",np.any(a>5))
#yukarıdaki işlemleri axis ifadsesini kullanarak satır vrya sütun bazındada yapabiliriz
print("satırlarda 5'ten küçük en az bir eleman varmı:",np.any(a<5,axis=1))
#yukarıdaki satır için 4 elemanlı bir dizi döndürüldü. dizinin her elemanı bir satırı temsil eder
print("sütunlardaki tüm elemanlar 2'den büyükmü:",np.all(a>5,axis=0))

a
 [[10  9  4]
 [ 9  8  8]
 [ 0  3  6]
 [ 4  4  4]]
tüm elemanlar 5'ten büyükmü: False
5'ten büyük değer varmı: True
satırlarda 5'ten küçük en az bir eleman varmı: [ True False  True  True]
sütunlardaki tüm elemanlar 2'den büyükmü: [False False False]


### koşulu sağlayan elemanlara erişim

In [39]:
a=np.array(np.random.randint(12,size=(4,3)))
print("a\n",a)
print("a>5 değerli sayılar",a[a>5])

a
 [[2 6 6]
 [9 0 2]
 [5 2 4]
 [3 3 7]]
a>5 değerli sayılar [6 6 9 7]


## NumPy Matematiksel İşlemler

In [40]:
a=np.arange(0,17,2)
print("a   :",a)
print("a+3 :",a+3) #==np.add(a,2)
print("a-5 :",a-5) #==np.subtract(a,5)
print("a*3 :",a*3) #np.multiply(0,3)
print("a^2 :",a**2) #==np.power(a,2)
print("3*a/1.2:",3*a/1.2) #==np.divide(3*a,1.2)

a   : [ 0  2  4  6  8 10 12 14 16]
a+3 : [ 3  5  7  9 11 13 15 17 19]
a-5 : [-5 -3 -1  1  3  5  7  9 11]
a*3 : [ 0  6 12 18 24 30 36 42 48]
a^2 : [  0   4  16  36  64 100 144 196 256]
3*a/1.2: [ 0.  5. 10. 15. 20. 25. 30. 35. 40.]


In [41]:
a=np.arange(0,17,2)
print(a)
print(np.add.reduce(a))
print(np.add.accumulate(a))

[ 0  2  4  6  8 10 12 14 16]
72
[ 0  2  6 12 20 30 42 56 72]


In [42]:
a=np.random.normal(0,1,30)
print("a     :\n",a)
print("mean  :",np.mean(a))
print("standart sapma:",np.std(a))
print("varyans:",np.var(a))
print("median",np.median(a))
print("minimum:",np.min(a))
print("maximum",np.max(a))

a     :
 [ 0.08234459  1.50988039 -2.78525239 -1.03040767  0.21056864 -1.01209723
 -1.66482785  0.05890845 -1.50941902 -0.98025237 -1.97239355 -1.23547931
  1.4059073  -0.06927444 -0.54271722  0.31584872 -0.27696751 -1.67652686
  0.25263806  1.05791057  1.5677103   0.49984275 -1.12979957  1.37343779
  0.66448394  1.04115435  1.84897068  0.37746192 -1.91525921  0.27364204]
mean  : -0.17533212390159827
standart sapma: 1.208714389389955
varyans: 1.4609904751183316
median 0.07062651770972811
minimum: -2.785252392617173
maximum 1.8489706792844316


## Broadcasting(Farklı Boyutlu Arraylerle Çalışma)

#### broad casting kurallaraı
kural 1: eğer iki array boyut sayısı olarak birbirinden farklı ise boyutu az olanın 
    boyutuna 1 ekleyerek çoğalt
    
    
kural 2:eğer eşleşmeyen boyut sayısı varsa 1 olan boyutu diğer arrayin boyutuna eşitle

kural 3:hala uyuşmazlık var ise hata üret

In [43]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print("a+b:\n",a+b)
c=np.ones((3,3))
print("a'nın boyutu:",a.ndim)
print("c'nin boyutu:",c.ndim)
print("a+c\n",a+c)

a+b:
 [2 4 6]
a'nın boyutu: 1
c'nin boyutu: 2
a+c
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [44]:
#ferklı bir örnek
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print("a:",a)
print("b:\n",b)
print("a+b\n",a+b)

a: [0 1 2]
b:
 [[0]
 [1]
 [2]]
a+b
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [45]:
a=np.arange(3).reshape((3,1))
b=np.arange(3)
print("a\n",a)
print("b",b)
print("a.shape",a.shape)
print("b.shape",b.shape)
print("a+b\n",a+b)

a
 [[0]
 [1]
 [2]]
b [0 1 2]
a.shape (3, 1)
b.shape (3,)
a+b
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [46]:
m=np.ones((3,2))
a=np.arange(3)
print("m\n",m)
print("a",a)
print("a+m:\n",a+m)

m
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
a [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,) (3,2) 